#!/usr/bin/env python3
"""
Additional state-dependence sensitivity controls for voluntary pain-regulation analyses.

This script is intended to be run AFTER run_state_dependence_sensitivity_controls.py.
It reads the cross-fitted trial table produced by that script and runs three families
of checks:

1) boundary-trimmed primary models, excluding trials close to rating/expected scale bounds;
2) available-room models, treating ceiling/floor room as the explanatory state variable;
3) null simulations testing whether the success-score interaction can be generated by
   bounded ratings plus the definition success = observed - expected.

Outputs are written as TSV files.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm
from scipy import stats
from patsy import dmatrix


def bh_fdr(pvals: pd.Series) -> pd.Series:
    p = pd.to_numeric(pvals, errors="coerce").to_numpy(dtype=float)
    out = np.full_like(p, np.nan, dtype=float)
    ok = np.isfinite(p)
    if ok.sum() == 0:
        return pd.Series(out, index=pvals.index)
    pv = p[ok]
    order = np.argsort(pv)
    ranked = pv[order]
    m = len(ranked)
    q = ranked * m / (np.arange(m) + 1.0)
    q = np.minimum.accumulate(q[::-1])[::-1]
    q = np.clip(q, 0, 1)
    tmp = np.empty_like(q)
    tmp[order] = q
    out[np.where(ok)[0]] = tmp
    return pd.Series(out, index=pvals.index)


def find_trial_table(args) -> Path:
    if args.trial_table:
        p = Path(args.trial_table)
        if not p.exists():
            raise FileNotFoundError(f"Trial table not found: {p}")
        return p
    if args.sensitivity_outdir:
        p = Path(args.sensitivity_outdir) / "crossfit_passive_baseline_trial_table.tsv"
        if not p.exists():
            raise FileNotFoundError(f"Could not find crossfit_passive_baseline_trial_table.tsv in {args.sensitivity_outdir}")
        return p
    raise ValueError("Provide --trial-table or --sensitivity-outdir")


def prepare_df(path: Path, use_crossfit: bool = True) -> pd.DataFrame:
    df = pd.read_csv(path, sep="\t")
    required = ["subject", "is_up_bin", "rating_raw_y", "rating_z_y", "temp_z", "trial_c", "run_c", "up_first"]
    for c in required:
        if c not in df.columns:
            raise ValueError(f"Required column missing: {c}")

    if use_crossfit and {"expected_raw_crossfit", "expected_z_crossfit", "success_raw_crossfit", "success_z_crossfit"}.issubset(df.columns):
        df["expected_raw"] = pd.to_numeric(df["expected_raw_crossfit"], errors="coerce")
        df["expected_z"] = pd.to_numeric(df["expected_z_crossfit"], errors="coerce")
        df["success_raw"] = pd.to_numeric(df["success_raw_crossfit"], errors="coerce")
        df["success_z"] = pd.to_numeric(df["success_z_crossfit"], errors="coerce")
        df["baseline_source"] = "crossfit"
    else:
        raw_col = "expected_pain_raw" if "expected_pain_raw" in df.columns else "expected_raw"
        z_col = "expected_pain_z" if "expected_pain_z" in df.columns else "expected_z"
        succ_raw_col = "reg_success_raw" if "reg_success_raw" in df.columns else "success_raw"
        succ_z_col = "reg_success_z" if "reg_success_z" in df.columns else "success_z"
        df["expected_raw"] = pd.to_numeric(df[raw_col], errors="coerce")
        df["expected_z"] = pd.to_numeric(df[z_col], errors="coerce")
        df["success_raw"] = pd.to_numeric(df[succ_raw_col], errors="coerce")
        df["success_z"] = pd.to_numeric(df[succ_z_col], errors="coerce")
        df["baseline_source"] = "original"

    df["rating_raw"] = pd.to_numeric(df["rating_raw_y"], errors="coerce")
    df["rating_z"] = pd.to_numeric(df["rating_z_y"], errors="coerce")
    df["is_up_bin"] = pd.to_numeric(df["is_up_bin"], errors="coerce")
    df["is_down_bin"] = 1 - df["is_up_bin"]

    # Available room in the instructed direction: room to increase for up, room to decrease for down.
    df["ceiling_margin_raw"] = 200.0 - df["expected_raw"]
    df["floor_margin_raw"] = df["expected_raw"] - 0.0
    df["available_room_raw"] = np.where(df["is_up_bin"].eq(1), df["ceiling_margin_raw"], df["floor_margin_raw"])

    # Boundary flags.
    df["rating_near_boundary_10"] = (df["rating_raw"] <= 10) | (df["rating_raw"] >= 190)
    df["expected_near_boundary_10"] = (df["expected_raw"] <= 10) | (df["expected_raw"] >= 190)
    df["expected_outside_scale"] = (df["expected_raw"] < 0) | (df["expected_raw"] > 200)
    df["available_room_low_10"] = df["available_room_raw"] <= 10

    # Center numeric predictors.
    for c in ["expected_raw", "expected_z", "available_room_raw", "ceiling_margin_raw", "floor_margin_raw", "temp_z", "trial_c", "run_c", "up_first"]:
        df[c + "_c"] = pd.to_numeric(df[c], errors="coerce") - pd.to_numeric(df[c], errors="coerce").mean()
    if "global_trial_z_subject" in df.columns:
        df["global_trial_z_c"] = pd.to_numeric(df["global_trial_z_subject"], errors="coerce") - pd.to_numeric(df["global_trial_z_subject"], errors="coerce").mean()
    else:
        df["global_trial_z_c"] = 0.0

    keep_cols = ["subject", "is_up_bin", "expected_raw", "expected_z", "success_raw", "success_z", "rating_raw", "rating_z", "available_room_raw"]
    df = df.dropna(subset=keep_cols).copy()
    return df


def fit_cluster_ols(df: pd.DataFrame, formula: str, model_name: str, note: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    m = smf.ols(formula, data=df).fit(cov_type="cluster", cov_kwds={"groups": df["subject"]})
    terms = []
    for term in m.params.index:
        terms.append({
            "model": model_name,
            "term": term,
            "beta": m.params[term],
            "se": m.bse[term],
            "t_or_z": m.tvalues[term],
            "p": m.pvalues[term],
            "n": int(m.nobs),
            "r2": getattr(m, "rsquared", np.nan),
            "formula": formula,
            "note": note,
        })
    terms = pd.DataFrame(terms)

    contrasts = []
    inter_terms = [t for t in m.params.index if ":" in t and "is_up_bin" in t and ("expected" in t or "available_room" in t)]
    for base_term in ["expected_raw_c", "expected_z_c", "available_room_raw_c"]:
        if base_term in m.params.index:
            inter = f"is_up_bin:{base_term}" if f"is_up_bin:{base_term}" in m.params.index else f"{base_term}:is_up_bin"
            b_down = m.params[base_term]
            se_down = m.bse[base_term]
            p_down = m.pvalues[base_term]
            contrasts.append({"model": model_name, "contrast": f"down_reference_slope__{base_term}", "estimate": b_down, "se": se_down, "z": m.tvalues[base_term], "p": p_down, "n": int(m.nobs), "formula": formula, "note": note})
            if inter in m.params.index:
                L = np.zeros(len(m.params))
                idx = list(m.params.index)
                L[idx.index(base_term)] = 1
                L[idx.index(inter)] = 1
                est = float(np.dot(L, m.params))
                var = float(np.dot(L, np.dot(m.cov_params(), L)))
                se = np.sqrt(max(var, 0))
                z = est / se if se > 0 else np.nan
                p = 2 * (1 - stats.norm.cdf(abs(z))) if np.isfinite(z) else np.nan
                contrasts.append({"model": model_name, "contrast": f"up_slope__{base_term}", "estimate": est, "se": se, "z": z, "p": p, "n": int(m.nobs), "formula": formula, "note": note})
                contrasts.append({"model": model_name, "contrast": f"up_minus_down_slope__{base_term}", "estimate": m.params[inter], "se": m.bse[inter], "z": m.tvalues[inter], "p": m.pvalues[inter], "n": int(m.nobs), "formula": formula, "note": note})
    return terms, pd.DataFrame(contrasts)


def run_models(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    cov = "+ temp_z_c + trial_c_c + run_c_c + global_trial_z_c + up_first_c + C(subject)"
    specs = []
    # Boundary-trimmed models.
    df_trim_rating = df.loc[~df["rating_near_boundary_10"]].copy()
    df_trim_expected = df.loc[~df["expected_near_boundary_10"] & ~df["expected_outside_scale"]].copy()
    df_trim_both = df.loc[~df["rating_near_boundary_10"] & ~df["expected_near_boundary_10"] & ~df["expected_outside_scale"]].copy()
    specs += [
        (df_trim_rating, "trim_rating_boundary_success_z", f"success_z ~ is_up_bin * expected_z_c {cov}", "Excludes trials with observed ratings <=10 or >=190."),
        (df_trim_expected, "trim_expected_boundary_success_z", f"success_z ~ is_up_bin * expected_z_c {cov}", "Excludes trials with expected raw pain <=10, >=190, or outside [0,200]."),
        (df_trim_both, "trim_rating_and_expected_boundary_success_z", f"success_z ~ is_up_bin * expected_z_c {cov}", "Excludes both observed-rating and expected-pain boundary trials."),
        (df_trim_rating, "trim_rating_boundary_success_raw", f"success_raw ~ is_up_bin * expected_raw_c {cov}", "Raw-scale companion excluding observed rating boundary trials."),
        (df_trim_expected, "trim_expected_boundary_success_raw", f"success_raw ~ is_up_bin * expected_raw_c {cov}", "Raw-scale companion excluding expected pain boundary trials."),
        (df_trim_both, "trim_rating_and_expected_boundary_success_raw", f"success_raw ~ is_up_bin * expected_raw_c {cov}", "Raw-scale companion excluding observed and expected boundary trials."),
    ]
    # Available-room-as-state models.
    specs += [
        (df, "available_room_state_success_z", f"success_z ~ is_up_bin * available_room_raw_c {cov}", "Tests whether success is better described by available room in the instructed direction."),
        (df, "available_room_state_success_raw", f"success_raw ~ is_up_bin * available_room_raw_c {cov}", "Raw-scale available-room state model."),
    ]

    all_terms = []
    all_contrasts = []
    for d, name, formula, note in specs:
        if len(d) < 50 or d["subject"].nunique() < 5:
            continue
        try:
            terms, contrasts = fit_cluster_ols(d, formula, name, note)
            all_terms.append(terms)
            all_contrasts.append(contrasts)
        except Exception as e:
            all_contrasts.append(pd.DataFrame([{"model": name, "contrast": "ERROR", "estimate": np.nan, "se": np.nan, "z": np.nan, "p": np.nan, "n": len(d), "formula": formula, "note": f"{note} ERROR: {e}"}]))
    terms = pd.concat(all_terms, ignore_index=True) if all_terms else pd.DataFrame()
    contrasts = pd.concat(all_contrasts, ignore_index=True) if all_contrasts else pd.DataFrame()
    if not terms.empty:
        terms["q_fdr"] = bh_fdr(terms["p"])
    if not contrasts.empty:
        contrasts["q_fdr"] = bh_fdr(contrasts["p"])
    return terms, contrasts


def null_simulation(df: pd.DataFrame, outdir: Path, n_sim: int, seed: int) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    cov_rhs = "is_up_bin + expected_raw_c + temp_z_c + trial_c_c + run_c_c + global_trial_z_c + up_first_c + C(subject)"
    null_formula = "rating_raw ~ " + cov_rhs
    null_model = smf.ols(null_formula, data=df).fit()
    fitted = null_model.fittedvalues.to_numpy()
    resid = null_model.resid.to_numpy()

    # Success model matrix. Fixed-effects included, no cluster covariance needed for null coefficient distribution.
    rhs = "is_up_bin * expected_raw_c + temp_z_c + trial_c_c + run_c_c + global_trial_z_c + up_first_c + C(subject)"
    X = dmatrix(rhs, df, return_type="dataframe")
    Xv = X.to_numpy()
    colnames = list(X.columns)
    inter_name = "is_up_bin:expected_raw_c" if "is_up_bin:expected_raw_c" in colnames else "expected_raw_c:is_up_bin"
    i_inter = colnames.index(inter_name)
    i_exp = colnames.index("expected_raw_c")

    y_obs = df["success_raw"].to_numpy()
    beta_obs = np.linalg.lstsq(Xv, y_obs, rcond=None)[0]
    obs_inter = beta_obs[i_inter]
    obs_down = beta_obs[i_exp]
    obs_up = obs_down + obs_inter

    rows = []
    for mode in ["unclipped", "clipped_0_200"]:
        for b in range(n_sim):
            eps = rng.choice(resid, size=len(df), replace=True)
            y = fitted + eps
            if mode == "clipped_0_200":
                y = np.clip(y, 0, 200)
            success = np.where(df["is_up_bin"].to_numpy() == 1, y - df["expected_raw"].to_numpy(), df["expected_raw"].to_numpy() - y)
            beta = np.linalg.lstsq(Xv, success, rcond=None)[0]
            inter = beta[i_inter]
            down = beta[i_exp]
            up = down + inter
            rows.append({"mode": mode, "simulation": b, "down_slope": down, "up_slope": up, "up_minus_down_slope": inter})
    sims = pd.DataFrame(rows)
    sims.to_csv(outdir / "null_simulation_coefficients.tsv", sep="\t", index=False)

    summary = []
    for mode, g in sims.groupby("mode"):
        vals = g["up_minus_down_slope"].to_numpy()
        summary.append({
            "mode": mode,
            "n_sim": len(vals),
            "observed_up_minus_down_slope_raw": obs_inter,
            "observed_down_slope_raw": obs_down,
            "observed_up_slope_raw": obs_up,
            "null_mean": np.nanmean(vals),
            "null_sd": np.nanstd(vals),
            "null_p025": np.nanquantile(vals, 0.025),
            "null_p500": np.nanquantile(vals, 0.500),
            "null_p975": np.nanquantile(vals, 0.975),
            "observed_percentile_rank": float(100.0 * np.mean(vals <= obs_inter)),
            "observed_within_central_95": bool(
                np.nanquantile(vals, 0.025) <= obs_inter <= np.nanquantile(vals, 0.975)
            ),
            "observed_below_null_min": bool(obs_inter < np.nanmin(vals)),
            "observed_above_null_max": bool(obs_inter > np.nanmax(vals)),
        })
    return pd.DataFrame(summary)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sensitivity-outdir", type=str, default=None, help="Directory from previous sensitivity-controls run")
    ap.add_argument("--trial-table", type=str, default=None, help="Path to crossfit_passive_baseline_trial_table.tsv")
    ap.add_argument("--outdir", type=str, required=True)
    ap.add_argument("--use-original-baseline", action="store_true", help="Use original baseline columns instead of cross-fitted columns")
    ap.add_argument("--n-sim", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=140)
    args = ap.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    trial_table = find_trial_table(args)
    df = prepare_df(trial_table, use_crossfit=not args.use_original_baseline)

    terms, contrasts = run_models(df)
    terms.to_csv(outdir / "additional_room_trimmed_model_terms.tsv", sep="\t", index=False)
    contrasts.to_csv(outdir / "additional_room_trimmed_model_contrasts.tsv", sep="\t", index=False)

    sim_summary = null_simulation(df, outdir, n_sim=args.n_sim, seed=args.seed)
    sim_summary.to_csv(outdir / "null_simulation_summary.tsv", sep="\t", index=False)

    desc = pd.DataFrame([
        {"quantity": "n_trials", "value": len(df)},
        {"quantity": "n_subjects", "value": df["subject"].nunique()},
        {"quantity": "n_rating_boundary_10", "value": int(df["rating_near_boundary_10"].sum())},
        {"quantity": "n_expected_boundary_10_or_outside", "value": int((df["expected_near_boundary_10"] | df["expected_outside_scale"]).sum())},
        {"quantity": "n_available_room_le_10", "value": int(df["available_room_low_10"].sum())},
        {"quantity": "baseline_source", "value": str(df["baseline_source"].iloc[0])},
    ])
    desc.to_csv(outdir / "additional_controls_descriptives.tsv", sep="\t", index=False)
    metadata = {
        "trial_table": str(trial_table),
        "outdir": str(outdir),
        "use_crossfit_baseline": not args.use_original_baseline,
        "n_sim": args.n_sim,
        "seed": args.seed,
    }
    (outdir / "run_metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(f"Outputs written to: {outdir}")

if __name__ == "__main__":
    main()
