function cfg = get_sessionwise_dcm_variant_config(variant)
%GET_SESSIONWISE_DCM_VARIANT_CONFIG Return the model-space configuration for one five-node DCM variant.
%
% Available variants:
%   control_value_descending_primary
%   control_value_bilateral_sensitivity
%   descending_affective_amygdala_left
%   descending_affective_amygdala_right
%   sensory_interoceptive_contralateral_right
%   sensory_interoceptive_ipsilateral_left
%
% The variants define theory-constrained five-node model spaces for
% control-value, affective-descending, and sensory-interoceptive pathways.

if nargin < 1 || isempty(variant)
    error('Specify a variant name.');
end
variant = char(string(variant));

cfg = get_sessionwise_dcm_base_config();
cfg.model_variant = variant;
cfg.echo_time_sec = 0.020;

switch lower(variant)
    case 'control_value_descending_primary'
        cfg.model_family = 'control_value_descending';
        cfg.model_role = 'primary_focused_model';
        cfg.rationale = ['Primary five-node control-value-descending model. ', ...
            'Left NAc is used because the original ds000140 paper emphasized regulation-related left NAc involvement; ', ...
            'a separate bilateral control-value model tests lateralization sensitivity. ', ...
            'vmPFC_mOFC uses the explicit combined vmPFC/mOFC ROI mask to match the node label.'];
        cfg.outdir = fullfile(cfg.derivatives_dir, 'dcm_control_value_descending_primary');
        cfg.roi_specs = roi_specs({ ...
            'dlPFC_IFJ_L', '^reg_dlPFC_IFJ_L$'; ...
            'vmPFC_mOFC', '^reg_vmPFC_mOFC$'; ...
            'NAc_L', '^reg_NAc_L$'; ...
            'pgACC_rACC', '^reg_pgACC_rACC$'; ...
            'PAG', '^reg_PAG_sphere$' ...
        });
        cfg.A_edges = bidir_edges({ ...
            'dlPFC_IFJ_L','vmPFC_mOFC'; ...
            'vmPFC_mOFC','NAc_L'; ...
            'vmPFC_mOFC','pgACC_rACC'; ...
            'pgACC_rACC','PAG' ...
        });
        cfg.B_edges = b_edges_for_all_inputs(cfg.input_names, cfg.A_edges);

    case 'control_value_bilateral_sensitivity'
        cfg.model_family = 'control_value';
        cfg.model_role = 'lateralization_sensitivity';
        cfg.rationale = ['Bilateral control-value sensitivity model. ', ...
            'Includes left/right dlPFC-IFJ and left/right NAc to test whether primary left-sided choices are lateralization-dependent. ', ...
            'The model remains five-node by omitting descending pgACC/PAG nodes.'];
        cfg.outdir = fullfile(cfg.derivatives_dir, 'dcm_control_value_bilateral_sensitivity');
        cfg.roi_specs = roi_specs({ ...
            'dlPFC_IFJ_L', '^reg_dlPFC_IFJ_L$'; ...
            'dlPFC_IFJ_R', '^reg_dlPFC_IFJ_R$'; ...
            'vmPFC_mOFC', '^reg_vmPFC_mOFC$'; ...
            'NAc_L', '^reg_NAc_L$'; ...
            'NAc_R', '^reg_NAc_R$' ...
        });
        cfg.A_edges = bidir_edges({ ...
            'dlPFC_IFJ_L','vmPFC_mOFC'; ...
            'dlPFC_IFJ_R','vmPFC_mOFC'; ...
            'vmPFC_mOFC','NAc_L'; ...
            'vmPFC_mOFC','NAc_R' ...
        });
        cfg.B_edges = b_edges_for_all_inputs(cfg.input_names, cfg.A_edges);

    case 'descending_affective_amygdala_left'
        cfg.model_family = 'descending_affective';
        cfg.model_role = 'affective_lateralization_left';
        cfg.rationale = ['Descending-affective model with left amygdala. ', ...
            'This model tests vmPFC/pgACC/PAG descending-modulation plus amygdala and hypothalamus pathways. ', ...
            'It is paired with a right-amygdala model to avoid an arbitrary unilateral amygdala claim.'];
        cfg.outdir = fullfile(cfg.derivatives_dir, 'dcm_descending_affective_amygdala_left');
        cfg.roi_specs = roi_specs({ ...
            'vmPFC_mOFC', '^reg_vmPFC_mOFC$'; ...
            'pgACC_rACC', '^reg_pgACC_rACC$'; ...
            'PAG', '^reg_PAG_sphere$'; ...
            'Amygdala_L', '^expl_amygdala_L$'; ...
            'Hypothalamus', '^expl_hypothalamus$' ...
        });
        cfg.A_edges = bidir_edges({ ...
            'vmPFC_mOFC','pgACC_rACC'; ...
            'pgACC_rACC','PAG'; ...
            'Amygdala_L','vmPFC_mOFC'; ...
            'Hypothalamus','PAG' ...
        });
        cfg.B_edges = b_edges_for_all_inputs(cfg.input_names, cfg.A_edges);

    case 'descending_affective_amygdala_right'
        cfg.model_family = 'descending_affective';
        cfg.model_role = 'affective_lateralization_right_sensitivity';
        cfg.rationale = ['Right-amygdala sensitivity model in the descending-affective family. ', ...
            'This directly tests whether affective-pathway conclusions depend on choosing left amygdala.'];
        cfg.outdir = fullfile(cfg.derivatives_dir, 'dcm_descending_affective_amygdala_right');
        cfg.roi_specs = roi_specs({ ...
            'vmPFC_mOFC', '^reg_vmPFC_mOFC$'; ...
            'pgACC_rACC', '^reg_pgACC_rACC$'; ...
            'PAG', '^reg_PAG_sphere$'; ...
            'Amygdala_R', '^expl_amygdala_R$'; ...
            'Hypothalamus', '^expl_hypothalamus$' ...
        });
        cfg.A_edges = bidir_edges({ ...
            'vmPFC_mOFC','pgACC_rACC'; ...
            'pgACC_rACC','PAG'; ...
            'Amygdala_R','vmPFC_mOFC'; ...
            'Hypothalamus','PAG' ...
        });
        cfg.B_edges = b_edges_for_all_inputs(cfg.input_names, cfg.A_edges);

    case 'sensory_interoceptive_contralateral_right'
        cfg.model_family = 'sensory_interoceptive';
        cfg.model_role = 'primary_contralateral_sensory_model';
        cfg.rationale = ['Primary sensory-interoceptive model uses right-hemisphere sensory nodes because thermal stimulation was delivered to the left forearm. ', ...
            'This matches the expected contralateral organization of ascending somatosensory/nociceptive pathways, with dACC/MCC as a midline node. ', ...
            'A left/ipsilateral model is provided as sensitivity.'];
        cfg.outdir = fullfile(cfg.derivatives_dir, 'dcm_sensory_interoceptive_contralateral_right');
        cfg.roi_specs = roi_specs({ ...
            'Thalamus_R', '^sensory_thalamus_R$'; ...
            'PosteriorInsula_R', '^sensory_posterior_insula_R$'; ...
            'AnteriorInsula_R', '^reg_anterior_insula_R$'; ...
            'dACC_MCC', '^sensory_dACC_MCC$'; ...
            'S2_Operculum_R', '^sensory_S2_operculum_R$' ...
        });
        cfg.A_edges = bidir_edges({ ...
            'Thalamus_R','PosteriorInsula_R'; ...
            'PosteriorInsula_R','AnteriorInsula_R'; ...
            'AnteriorInsula_R','dACC_MCC'; ...
            'Thalamus_R','S2_Operculum_R' ...
        });
        cfg.B_edges = b_edges_for_all_inputs(cfg.input_names, cfg.A_edges);

    case 'sensory_interoceptive_ipsilateral_left'
        cfg.model_family = 'sensory_interoceptive';
        cfg.model_role = 'ipsilateral_sensory_sensitivity';
        cfg.rationale = ['Left/ipsilateral sensory-interoceptive sensitivity model. ', ...
            'This preserves the original left-sided sensory variant but is interpreted only as lateralization sensitivity, not as the primary sensory model.'];
        cfg.outdir = fullfile(cfg.derivatives_dir, 'dcm_sensory_interoceptive_ipsilateral_left');
        cfg.roi_specs = roi_specs({ ...
            'Thalamus_L', '^sensory_thalamus_L$'; ...
            'PosteriorInsula_L', '^sensory_posterior_insula_L$'; ...
            'AnteriorInsula_L', '^reg_anterior_insula_L$'; ...
            'dACC_MCC', '^sensory_dACC_MCC$'; ...
            'S2_Operculum_L', '^sensory_S2_operculum_L$' ...
        });
        cfg.A_edges = bidir_edges({ ...
            'Thalamus_L','PosteriorInsula_L'; ...
            'PosteriorInsula_L','AnteriorInsula_L'; ...
            'AnteriorInsula_L','dACC_MCC'; ...
            'Thalamus_L','S2_Operculum_L' ...
        });
        cfg.B_edges = b_edges_for_all_inputs(cfg.input_names, cfg.A_edges);

    otherwise
        error('Unknown DCM variant: %s', variant);
end

% Conservative driving-input policy: every experimental input is allowed to
% drive every selected node. This prevents condition responses from being
% forced into B-modulatory parameters by omitted C inputs.
cfg.C_drives = all_input_drives(cfg.input_names, {cfg.roi_specs.name});
end

% -------------------------------------------------------------------------
% Helpers
% -------------------------------------------------------------------------
function specs = roi_specs(C)
specs = struct('name', {}, 'pattern', {});
for i = 1:size(C,1)
    specs(i).name = C{i,1}; %#ok<AGROW>
    specs(i).pattern = C{i,2}; %#ok<AGROW>
end
end

function E = bidir_edges(pairs)
E = {};
for i = 1:size(pairs,1)
    a = pairs{i,1};
    b = pairs{i,2};
    E(end+1,:) = {a,b}; %#ok<AGROW>
    E(end+1,:) = {b,a}; %#ok<AGROW>
end
end

function B = b_edges_for_all_inputs(input_names, A_edges)
B = {};
for ui = 1:numel(input_names)
    inp = input_names{ui};
    for ei = 1:size(A_edges,1)
        B(end+1,:) = {inp, A_edges{ei,1}, A_edges{ei,2}}; %#ok<AGROW>
    end
end
end

function C = all_input_drives(input_names, roi_names)
C = {};
for ui = 1:numel(input_names)
    for ri = 1:numel(roi_names)
        C(end+1,:) = {input_names{ui}, roi_names{ri}}; %#ok<AGROW>
    end
end
end
