%% Run all six run-separated, rating-adjusted DCM/PEB models.
clear; clc;

variants = { ...
    'control_value_descending_primary', ...
    'control_value_bilateral_sensitivity', ...
    'descending_affective_amygdala_left', ...
    'descending_affective_amygdala_right', ...
    'sensory_interoceptive_contralateral_right', ...
    'sensory_interoceptive_ipsilateral_left' ...
};

for i = 1:numel(variants)
    fprintf('\n============================================================\n');
    fprintf('SESSIONWISE DCM VARIANT %d/%d: %s\n', i, numel(variants), variants{i});
    fprintf('============================================================\n');
    run_sessionwise_dcm_variant(variants{i}, 'full');
end
